-- Generated by tools/wowhead_import.py from https://www.wowhead.com/mop-classic/ - DO NOT EDIT BY HAND.
-- Generated: 2026-09-14T10:04:45Z. Only fields the generated database is missing are written here;
-- Database/DB.lua applies them on top of Database/Data at load time (Schema key names).
local _, ns = ...
ns.Overrides = ns.Overrides or {}
ns.Overrides.wowhead = {
    quests = {},
    npcs = {},
    objects = {},
    items = {},
}
