-- Generated by tools/wowhead_import.py from https://www.wowhead.com/mop-classic/ - DO NOT EDIT BY HAND.
-- Generated: 2026-09-14T17:48:16Z. Only fields the generated database is missing are written here;
-- Database/DB.lua applies them on top of Database/Data at load time (Schema key names).
local _, ns = ...
ns.Overrides = ns.Overrides or {}
ns.Overrides.wowhead = {
    quests = {
        [5381] = {startedBy = {[1] = {11624}}},
    },
    npcs = {},
    objects = {},
    items = {},
}
