-- Map/Icons.lua: icon name -> texture path and the target -> icon mapping.
-- The pin_*.tga files are generated by the texture script; a missing file only makes the
-- texture invisible in-game, so every lookup degrades to a path instead of erroring.
local _, ns = ...

local M = {}
ns.Icons = M

local type, pairs, tostring = type, pairs, tostring
local byte, len, sqrt, floor = string.byte, string.len, math.sqrt, math.floor

local TEXTURE_ROOT = "Interface\\AddOns\\PandaQuest\\Textures\\"

-- Contract name -> file below Textures/. The first block is ns.Const.ICON_KINDS and must stay in sync with it; the second is the dot and its ring added later,
-- which is not part of that older contract. There are no per-kind gathering glyphs:
-- a gathering node is the same dot as an objective spawn, tinted by kind (see KIND_COLORS).
local FILES = {
    available            = "pin_available.tga",
    available_gray       = "pin_available_gray.tga",
    available_repeatable = "pin_available_repeatable.tga",
    complete             = "pin_complete.tga",
    complete_repeatable  = "pin_complete_repeatable.tga",
    slay                 = "pin_slay.tga",
    loot                 = "pin_loot.tga",
    object               = "pin_object.tga",
    talk                 = "pin_talk.tga",
    event                = "pin_event.tga",
    itemuse              = "pin_itemuse.tga",
    explore              = "pin_explore.tga",
    pickup               = "pin_pickup.tga",
    custom               = "pin_custom.tga",
    glow                 = "arrow_glow.tga",
    arrow                = "arrow.tga",
    -- The objective dot and its ring.
    node                 = "node.tga",
    node_outline         = "node_outline.tga",
}
M.FILES = FILES

-- Fallbacks for names whose texture may not have been generated yet.
local ALIAS = {
    available_gray       = "available",
    available_repeatable = "available",
    complete_repeatable  = "complete",
    pickup               = "available",
    itemuse              = "object",
    event                = "object",
    explore              = "custom",
}

-- Resolved paths are cached: Pins asks for them once per pin and per redraw.
local pathCache = {}

--- Icons.Get(name) -> texturePath. Unknown names fall back to "custom" so a pin is always drawn.
function M.Get(name)
    if type(name) ~= "string" then name = "custom" end
    local cached = pathCache[name]
    if cached then return cached end
    local file = FILES[name] or FILES[ALIAS[name] or ""] or FILES.custom
    local path = TEXTURE_ROOT .. file
    pathCache[name] = path
    return path
end

--- Icons.Exists(name) -> bool. True when the contract knows this icon name.
function M.Exists(name)
    return type(name) == "string" and FILES[name] ~= nil
end

--- Icons.GetRoot() -> "Interface\\AddOns\\PandaQuest\\Textures\\"
function M.GetRoot()
    return TEXTURE_ROOT
end

---------------------------------------------------------------------------
-- Target -> icon
---------------------------------------------------------------------------

-- Fallbacks when Objectives did not stamp target.icon.
local KIND_ICON = {
    TURNIN  = "complete",
    PICKUP  = "available",
    ITEMUSE = "itemuse",
    EXPLORE = "explore",
    CUSTOM  = "custom",
}

local ENTITY_ICON = {
    npc    = "slay",
    object = "object",
    item   = "loot",
    area   = "explore",
}

--- Icons.NameForTarget(target) -> icon name (never nil).
function M.NameForTarget(target)
    if type(target) ~= "table" then return "custom" end
    local name = target.icon
    if type(name) == "string" and FILES[name] then
        return name
    end
    local byKind = KIND_ICON[target.kind]
    if byKind then return byKind end
    return ENTITY_ICON[target.entityType] or "slay"
end

--- Icons.GetForTarget(target) -> texturePath, iconName
function M.GetForTarget(target)
    local name = M.NameForTarget(target)
    return M.Get(name), name
end

---------------------------------------------------------------------------
-- Sizes (profile.map.iconScale / minimapIconScale)
---------------------------------------------------------------------------

local BASE_SIZE = 16               -- world-map pin edge in pixels at scale 1.0
local BASE_MINIMAP_SIZE = 10       -- Smaller than the world map, the owner could not read it
local MIN_SIZE, MAX_SIZE = 4, 64

-- Objective dots are smaller again than the `!`/`?` icons they replaced: those are
-- glyphs that have to stay legible, a dot only has to be visible.
local BASE_NODE_SIZE = 11
local BASE_NODE_MINIMAP_SIZE = 7
local CLUSTER_FACTOR = 1.35        -- pfQuest draws a cluster at 18 px where a node is 14

-- node.tga fills 75 % of its texture, node_outline.tga's ring reaches 88.75 % of its own. Drawing
-- the ring at `0.85 * size + 2.5` puts roughly 1.1 screen pixels of dark rim outside the dot at
-- every size we use, instead of a rim that vanishes on the minimap and bloats on the world map.
local function outlineSizeFor(size)
    return size * 0.85 + 2.5
end

local function mapProfile()
    local PQ = ns.PQ
    local profile = PQ and PQ.db and PQ.db.profile
    return profile and profile.map
end

--- Icons.GetScale(minimap) -> number. profile.map.iconScale / minimapIconScale, clamped to 0.25..4.
function M.GetScale(minimap)
    local map = mapProfile()
    local scale = map and (minimap and map.minimapIconScale or map.iconScale)
    if type(scale) ~= "number" or scale ~= scale then scale = 1.0 end
    if scale < 0.25 then scale = 0.25 end
    if scale > 4 then scale = 4 end
    return scale
end

--- Icons.GetSize(minimap) -> pixels, honouring profile.map.iconScale.
function M.GetSize(minimap)
    local base = minimap and BASE_MINIMAP_SIZE or BASE_SIZE
    local size = base * M.GetScale(minimap)
    if size < MIN_SIZE then size = MIN_SIZE end
    if size > MAX_SIZE then size = MAX_SIZE end
    return size
end

--- Icons.GetNodeScale() -> number. profile.map.nodeScale, clamped to 0.25..4. Separate from
-- iconScale so a player can shrink the dots without shrinking the `!` and `?` glyphs.
function M.GetNodeScale()
    local map = mapProfile()
    local scale = map and map.nodeScale
    if type(scale) ~= "number" or scale ~= scale then scale = 1.0 end
    if scale < 0.25 then scale = 0.25 end
    if scale > 4 then scale = 4 end
    return scale
end

--- Icons.GetNodeSize(minimap, cluster) -> pixels for an objective dot.
function M.GetNodeSize(minimap, cluster)
    local base = minimap and BASE_NODE_MINIMAP_SIZE or BASE_NODE_SIZE
    local size = base * M.GetScale(minimap) * M.GetNodeScale()
    if cluster then size = size * CLUSTER_FACTOR end
    if size < MIN_SIZE then size = MIN_SIZE end
    if size > MAX_SIZE then size = MAX_SIZE end
    return size
end

M.BASE_SIZE = BASE_SIZE
M.BASE_MINIMAP_SIZE = BASE_MINIMAP_SIZE
M.BASE_NODE_SIZE = BASE_NODE_SIZE
M.BASE_NODE_MINIMAP_SIZE = BASE_NODE_MINIMAP_SIZE
M.CLUSTER_FACTOR = CLUSTER_FACTOR

---------------------------------------------------------------------------
-- Quest colour
---------------------------------------------------------------------------

-- pfQuest's str2rgb (_reference/pfQuest/map.lua:116) ported to Lua 5.1: a stable hash of the quest
-- name folded into 24 bits and split into three bytes. The point is that it needs no palette --
-- every quest gets its own colour, the same colour in every session and for every player, and two
-- dots of the same colour are two spawns of the same quest.
--
-- The intermediate values stay well inside the 2^53 a double represents exactly: `counter` is
-- reduced modulo 4294967279 at the top of each iteration, so the largest product formed is about
-- 2.1e14.
local rgbCache = {}

local function str2rgb(text)
    local counter = 1
    local l = len(text)
    for i = 1, l, 3 do
        counter = (counter * 8161) % 4294967279
            + (byte(text, i) * 16776193)
            + ((byte(text, i + 1) or (l - i + 256)) * 8372226)
            + ((byte(text, i + 2) or (l - i + 256)) * 3932164)
    end
    local hash = (counter % 4294967291) % 16777216
    local r = (hash - (hash % 65536)) / 65536
    local g = ((hash - r * 65536) - ((hash - r * 65536) % 256)) / 256
    local b = hash - r * 65536 - g * 256
    return r / 255, g / 255, b / 255
end

-- Perceived brightness of the hash, and the floor we insist on. A raw str2rgb value is uniform
-- over the whole cube, so roughly a fifth of all quests would land on a colour too dark to see
-- against the world map's terrain. Scaling the darkest ones up keeps the hash deterministic (the
-- correction is a pure function of the colour) while giving every quest a visible dot.
local MIN_LUMA = 0.42

local function lumaOf(r, g, b)
    return sqrt(0.299 * r * r + 0.587 * g * g + 0.114 * b * b)
end

local function brighten(r, g, b)
    local luma = lumaOf(r, g, b)
    if luma >= MIN_LUMA then return r, g, b end
    -- Scaling the three channels keeps the hue, and is the right answer whenever it fits inside
    -- the cube. A colour like (0.05, 0.05, 0.95) does not fit -- scaling it would clamp the blue
    -- and leave the result as dark as it started -- so those blend towards white instead, which
    -- always reaches the floor because white's luma is 1. Twelve bisection steps put the result
    -- within 1/4096 of the floor, and the whole thing is still a pure function of the hash.
    if luma > 0.0001 then
        local k = MIN_LUMA / luma
        if r * k <= 1 and g * k <= 1 and b * k <= 1 then
            return r * k, g * k, b * k
        end
    end
    local lo, hi = 0, 1
    for _ = 1, 12 do
        local t = (lo + hi) / 2
        if lumaOf(r + (1 - r) * t, g + (1 - g) * t, b + (1 - b) * t) < MIN_LUMA then
            lo = t
        else
            hi = t
        end
    end
    return r + (1 - r) * hi, g + (1 - g) * hi, b + (1 - b) * hi
end

--- Icons.QuestColor(text) -> r, g, b (0..1). Deterministic, cached, never nil.
function M.QuestColor(text)
    if type(text) ~= "string" or text == "" then text = "PandaQuest" end
    local cached = rgbCache[text]
    if cached then return cached[1], cached[2], cached[3] end
    local r, g, b = brighten(str2rgb(text))
    rgbCache[text] = { r, g, b }
    return r, g, b
end

---------------------------------------------------------------------------
-- Gathering colour
---------------------------------------------------------------------------

-- One colour per gathering kind, on the same dot and ring as an objective spawn. The owner played
-- with a pickaxe, a sprig, a fish, a chest and a skull on the map and called them "really
-- confusing": at 16 px they were five different pictures competing with the quest dots, and a
-- mining spot is what they wanted to find at a glance - "a small yellow ball". So mining is
-- yellow because they asked for yellow, and the other four are spread round the hue circle far
-- enough from it and from each other to be told apart on a 7 px minimap dot. Every one of them is
-- well above MIN_LUMA, the floor that keeps a quest dot readable on the map's terrain, and the
-- dark ring (node_outline.tga) carries them on snow and sand alike, exactly as it does the quests.
-- A quest's colour is a hash and can land anywhere, so these cannot be kept away from every quest;
-- what keeps the two apart is that a gathering dot is always one of these five.
local KIND_COLORS = {
    mine  = { 1.00, 0.85, 0.10 },       -- yellow
    herb  = { 0.35, 0.90, 0.30 },       -- green
    fish  = { 0.30, 0.70, 1.00 },       -- blue
    chest = { 0.80, 0.50, 1.00 },       -- violet
    rare  = { 1.00, 0.35, 0.30 },       -- red
}
M.KIND_COLORS = KIND_COLORS

--- Icons.KindColor(kind) -> r, g, b. A kind this table does not know gets plain white rather than
-- nil, so a kind added to Nodes/Professions.lua before it is given a colour still draws.
function M.KindColor(kind)
    local color = KIND_COLORS[kind]
    if not color then return 1, 1, 1 end
    return color[1], color[2], color[3]
end

--- Icons.ColorForSpec(spec) -> r, g, b. A gathering node is coloured by its kind. Everything else
-- takes the quest *name*, with the quest id and then the entity name as fallbacks so
-- an unnamed target still gets a stable dot.
function M.ColorForSpec(spec)
    if spec and spec.layer == "profession" then return M.KindColor(spec.kind) end
    local target = spec and spec.targets and spec.targets[1]
    if not target then return M.QuestColor(nil) end
    local text = target.questTitle
    if type(text) ~= "string" or text == "" then
        text = target.questID and ("quest:" .. tostring(target.questID))
            or target.entityName or target.key or nil
    end
    return M.QuestColor(text)
end

---------------------------------------------------------------------------
-- Pin appearance
---------------------------------------------------------------------------

-- Layers that are drawn as a coloured dot rather than as an icon. Quest givers and turn-ins keep
-- their `!` and `?`: those are already right. Gathering nodes are dots too, the
-- same size and with the same ring as the objective dots the owner had already accepted.
local DOT_LAYERS = { objective = true, profession = true }

--- Icons.UsesDot(spec) -> bool
function M.UsesDot(spec)
    return spec ~= nil and DOT_LAYERS[spec.layer] == true
end

--- Icons.ApplyNode(pin, spec, minimap) -> "dot"|"icon", size
--
-- Draws one pin: a dot tinted with the quest colour (plus its dark ring and, for a cluster, the
-- spawn count) or the glyph the target asks for. `pin` is the frame Map/Pins.lua pooled; it is
-- expected to carry `texture`, and optionally `outline` and `count`.
--
-- The size is a SCREEN size divided by ns.MapCompat.GetPinScaleFactor(pin): the pin
-- is a child of the world map canvas, so a map addon that scales the canvas would otherwise scale
-- the pin with it.
function M.ApplyNode(pin, spec, minimap)
    if not pin or not pin.texture or not pin.texture.SetTexture then return nil end
    local texture, outline, count = pin.texture, pin.outline, pin.count
    local dot = M.UsesDot(spec)
    local cluster = dot and spec.count ~= nil and spec.count > 1
    local size = dot and M.GetNodeSize(minimap, cluster) or M.GetSize(minimap)

    local factor = 1
    local Compat = ns.MapCompat
    if Compat and Compat.GetPinScaleFactor then factor = Compat.GetPinScaleFactor(pin) end
    local frameSize = size * factor

    if pin.SetSize then pin:SetSize(frameSize, frameSize) end
    if texture.SetSize then texture:SetSize(frameSize, frameSize) end

    if dot then
        texture:SetTexture(M.Get("node"))
        if texture.SetVertexColor then
            local r, g, b = M.ColorForSpec(spec)
            texture:SetVertexColor(r, g, b, 1)
        end
        if outline then
            outline:SetTexture(M.Get("node_outline"))
            if outline.SetSize then
                local os = outlineSizeFor(size) * factor
                outline:SetSize(os, os)
            end
            outline:Show()
        end
        -- The count goes on the world map only. A cluster is drawn larger on the minimap too, so
        -- "there are several here" still reads there, but a digit under 6 pt on a 9 px dot is not
        -- information -- it is the smear the smaller minimap dots exist to get rid of.
        if count then
            if cluster and not minimap then
                count:SetText(tostring(spec.count))
                if count.SetFont and count.GetFont then
                    local path, _, flags = count:GetFont()
                    if path then
                        local points = floor(frameSize * 0.72)
                        if points < 6 then points = 6 end
                        count:SetFont(path, points, flags or "OUTLINE")
                    end
                end
                count:Show()
            else
                count:Hide()
            end
        end
        return "dot", frameSize
    end

    local path = M.GetForTarget(spec and spec.targets and spec.targets[1])
    texture:SetTexture(path)
    if texture.SetVertexColor then texture:SetVertexColor(1, 1, 1, 1) end
    if outline then outline:Hide() end
    if count then count:Hide() end
    return "icon", frameSize
end

--- Applies the icon of `target` (and the configured size) to a texture + its owning frame.
-- Returns the icon name that was used, or nil when there was nothing to draw on.
function M.Apply(texture, target, minimap, frame)
    if not texture or not texture.SetTexture then return nil end
    local path, name = M.GetForTarget(target)
    texture:SetTexture(path)
    local size = M.GetSize(minimap)
    if frame and frame.SetSize then frame:SetSize(size, size) end
    if texture.SetSize then texture:SetSize(size, size) end
    return name
end

function M.OnProfileChanged()
    -- Paths do not depend on the profile, but the cache is cheap to drop and keeps a reloaded
    -- texture set (make_textures.py rerun) from sticking around.
    for k in pairs(pathCache) do pathCache[k] = nil end
end
