-- Map/Icons.lua: icon name -> texture path and the target -> icon mapping (docs/06 section 10).
-- The pin_*.tga files are generated by tools/make_textures.py; a missing file only makes the
-- texture invisible in-game, so every lookup degrades to a path instead of erroring.
local _, ns = ...

local M = {}
ns.Icons = M

local type, pairs = type, pairs

local TEXTURE_ROOT = "Interface\\AddOns\\PandaQuest\\Textures\\"

-- Contract name -> file below Textures/. Keep in sync with ns.Const.ICON_KINDS.
local FILES = {
    available            = "pin_available.tga",
    available_gray       = "pin_available_gray.tga",
    available_repeatable = "pin_available_repeatable.tga",
    complete             = "pin_complete.tga",
    complete_repeatable  = "pin_complete_repeatable.tga",
    slay                 = "pin_slay.tga",
    loot                 = "pin_loot.tga",
    object               = "pin_object.tga",
    talk                 = "pin_talk.tga",
    event                = "pin_event.tga",
    itemuse              = "pin_itemuse.tga",
    explore              = "pin_explore.tga",
    pickup               = "pin_pickup.tga",
    custom               = "pin_custom.tga",
    glow                 = "arrow_glow.tga",
    arrow                = "arrow.tga",
}
M.FILES = FILES

-- Fallbacks for names whose texture may not have been generated yet.
local ALIAS = {
    available_gray       = "available",
    available_repeatable = "available",
    complete_repeatable  = "complete",
    pickup               = "available",
    itemuse              = "object",
    event                = "object",
    explore              = "custom",
}

-- Resolved paths are cached: Pins asks for them once per pin and per redraw.
local pathCache = {}

--- Icons.Get(name) -> texturePath. Unknown names fall back to "custom" so a pin is always drawn.
function M.Get(name)
    if type(name) ~= "string" then name = "custom" end
    local cached = pathCache[name]
    if cached then return cached end
    local file = FILES[name] or FILES[ALIAS[name] or ""] or FILES.custom
    local path = TEXTURE_ROOT .. file
    pathCache[name] = path
    return path
end

--- Icons.Exists(name) -> bool. True when the contract knows this icon name.
function M.Exists(name)
    return type(name) == "string" and FILES[name] ~= nil
end

--- Icons.GetRoot() -> "Interface\\AddOns\\PandaQuest\\Textures\\"
function M.GetRoot()
    return TEXTURE_ROOT
end

---------------------------------------------------------------------------
-- Target -> icon
---------------------------------------------------------------------------

-- Fallbacks when Objectives did not stamp target.icon.
local KIND_ICON = {
    TURNIN  = "complete",
    PICKUP  = "available",
    ITEMUSE = "itemuse",
    EXPLORE = "explore",
    CUSTOM  = "custom",
}

local ENTITY_ICON = {
    npc    = "slay",
    object = "object",
    item   = "loot",
    area   = "explore",
}

--- Icons.NameForTarget(target) -> icon name (never nil).
function M.NameForTarget(target)
    if type(target) ~= "table" then return "custom" end
    local name = target.icon
    if type(name) == "string" and FILES[name] then
        return name
    end
    local byKind = KIND_ICON[target.kind]
    if byKind then return byKind end
    return ENTITY_ICON[target.entityType] or "slay"
end

--- Icons.GetForTarget(target) -> texturePath, iconName
function M.GetForTarget(target)
    local name = M.NameForTarget(target)
    return M.Get(name), name
end

---------------------------------------------------------------------------
-- Sizes (profile.map.iconScale / minimapIconScale)
---------------------------------------------------------------------------

local BASE_SIZE = 16               -- world-map pin edge in pixels at scale 1.0
local BASE_MINIMAP_SIZE = 12
local MIN_SIZE, MAX_SIZE = 6, 64

local function mapProfile()
    local PQ = ns.PQ
    local profile = PQ and PQ.db and PQ.db.profile
    return profile and profile.map
end

--- Icons.GetScale(minimap) -> number. profile.map.iconScale / minimapIconScale, clamped to 0.25..4.
function M.GetScale(minimap)
    local map = mapProfile()
    local scale = map and (minimap and map.minimapIconScale or map.iconScale)
    if type(scale) ~= "number" or scale ~= scale then scale = 1.0 end
    if scale < 0.25 then scale = 0.25 end
    if scale > 4 then scale = 4 end
    return scale
end

--- Icons.GetSize(minimap) -> pixels, honouring profile.map.iconScale.
function M.GetSize(minimap)
    local base = minimap and BASE_MINIMAP_SIZE or BASE_SIZE
    local size = base * M.GetScale(minimap)
    if size < MIN_SIZE then size = MIN_SIZE end
    if size > MAX_SIZE then size = MAX_SIZE end
    return size
end

M.BASE_SIZE = BASE_SIZE
M.BASE_MINIMAP_SIZE = BASE_MINIMAP_SIZE

--- Applies the icon of `target` (and the configured size) to a texture + its owning frame.
-- Returns the icon name that was used, or nil when there was nothing to draw on.
function M.Apply(texture, target, minimap, frame)
    if not texture or not texture.SetTexture then return nil end
    local path, name = M.GetForTarget(target)
    texture:SetTexture(path)
    local size = M.GetSize(minimap)
    if frame and frame.SetSize then frame:SetSize(size, size) end
    if texture.SetSize then texture:SetSize(size, size) end
    return name
end

function M.OnProfileChanged()
    -- Paths do not depend on the profile, but the cache is cheap to drop and keeps a reloaded
    -- texture set (make_textures.py rerun) from sticking around.
    for k in pairs(pathCache) do pathCache[k] = nil end
end
